# Generated by Django 4.2.30 on 2026-07-30 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('photo_original', models.URLField(verbose_name="URL de l'image")),
                ('photo_modifier', models.ImageField(upload_to='images_modifier/')),
            ],
        ),
    ]
