# Generated by Django 4.2.30 on 2026-07-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='photo_original_fichie',
            field=models.ImageField(blank=True, null=True, upload_to='images_originales/'),
        ),
    ]
