# Generated by Django 4.2.30 on 2026-07-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_table_photo_original_fichie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='photo_modifier',
            field=models.ImageField(blank=True, null=True, upload_to='images_modifier/'),
        ),
    ]
