# Generated by Django 4.2.30 on 2026-10-07 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_alter_table_photo_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
